/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VUE;

import CONTROLEUR.TraitementCaisse;
import CONTROLEUR.TraitementEtudiant;
import MODELE.Caisse;
import MODELE.Etudiant;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class CaisseForm extends javax.swing.JFrame {

    /**
     * Creates new form CaisseForm
     */
    public CaisseForm() {
        initComponents();
        //Ajout récent
        jLabel9.setVisible(false);
        jComboBox1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Matricule");

        jLabel2.setText("Prenom");

        jLabel3.setText("Nom");

        jLabel4.setText("Filiere");

        jLabel5.setText("Niveau");

        jLabel6.setText("Montant");

        jLabel7.setText("Objet");

        jLabel9.setText("Mois");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inscription", "Scolarite" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Rechercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Payer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Octobre", "Novembre", "Decembre", "Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(86, 86, 86)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)))
                .addComponent(jButton3)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Boutton Quitter
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
//        String text = jComboBox3.getSelectedItem().toString();
//        if(text.equalsIgnoreCase("Inscription")){
//            jTextField4.setText("200000");
//            jTextField4.setEditable(false);
//        }// TODO add your handling code here:
//        else if(text.equalsIgnoreCase("Scolarite")){
//            String niveau = jTextField8.getText();
//            if(niveau.equals("L1")){
//                jTextField4.setText("70000");
//                jTextField4.setEditable(false);
//            }
//            else if(niveau.equals("L2")){
//                jTextField4.setText("80000");
//                jTextField4.setEditable(false);
//            }
//            
//             else if(niveau.equals("L3")){
//                jTextField4.setText("90000");
//                jTextField4.setEditable(false);
//            }
//            
//             else if(niveau.equals("M1")){
//                jTextField4.setText("100000");
//                jTextField4.setEditable(false);
//            }
//            
//             else if(niveau.equals("M2")){
//                jTextField4.setText("150000");
//                jTextField4.setEditable(false);               
//            }
//            
//            //jTextField4.setText("");
//            //jTextField4.setEditable(true);
//        }
           String text = jComboBox3.getSelectedItem().toString();
    if(text.equalsIgnoreCase("Inscription")){
        jTextField4.setText("200000");
        jTextField4.setEditable(false);

        // Cacher le champ Mois
        jLabel9.setVisible(false);
        jComboBox1.setVisible(false);
    } else if(text.equalsIgnoreCase("Scolarite")){
        String niveau = jTextField8.getText();
        if(niveau.equals("L1")){
            jTextField4.setText("70000");
        } else if(niveau.equals("L2")){
            jTextField4.setText("80000");
        } else if(niveau.equals("L3")){
            jTextField4.setText("90000");
        } else if(niveau.equals("M1")){
            jTextField4.setText("100000");
        } else if(niveau.equals("M2")){
            jTextField4.setText("150000");
        }
        jTextField4.setEditable(false);

        // Afficher le champ Mois
        jLabel9.setVisible(true);
        jComboBox1.setVisible(true);
    }

    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        jTextField2.setEditable(false);        // TODO add your handling cfode here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Boutton rechercher
        System.out.println("Called function");
        String matricule =jTextField1.getText();
         if(matricule == null || matricule.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir le matricule");
            return;
        }
        TraitementCaisse tp = new TraitementCaisse();
        Etudiant etudiant = tp.rechercherEtudiant(matricule);
       if(etudiant==null){
           // Creer un message derreur 
           JOptionPane.showMessageDialog(null, "L'étudiant n'est pas dans la base de donnée");
            return;
       }
       
        jTextField2.setText(etudiant.getPrenom());
        jTextField3.setText(etudiant.getNom());
        jTextField7.setText(etudiant.getFiliere());
        jTextField8.setText(etudiant.getNiveau());
//        String matricule = jTextField1.getText();
//    if (matricule == null || matricule.trim().equals("")) {
//        JOptionPane.showMessageDialog(null, "Veuillez remplir le matricule");
//        return;
//    }
//
//    TraitementCaisse tp = new TraitementCaisse();
//    Etudiant etudiant = tp.rechercherEtudiant(matricule);
//    if (etudiant == null) {
//        JOptionPane.showMessageDialog(null, "L'étudiant n'est pas dans la base de données");
//        return;
//    }
//
//    jTextField2.setText(etudiant.getPrenom());
//    jTextField3.setText(etudiant.getNom());
//    jTextField7.setText(etudiant.getFiliere());
//    jTextField8.setText(etudiant.getNiveau());
//
//    // Vérification de la situation de paiement
//    boolean aJourInscription = tp.estEtudiantAJour(matricule, "Inscription");
//    boolean aJourScolarite = tp.estEtudiantAJour(matricule, "Scolarite");
//
//    String message = "État des paiements :\n";
//    message += "- Inscription : " + (aJourInscription ? "À jour ✅" : "En retard ❌") + "\n";
//    message += "- Scolarité : " + (aJourScolarite ? "À jour ✅" : "En retard ❌");
//
//    JOptionPane.showMessageDialog(null, message);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Boutton Payer
        System.out.println("Called function payer");
        String Matricule = jTextField1.getText();
        String Objet = jComboBox3.getSelectedItem().toString();
        String Mois = jComboBox1.getSelectedItem().toString();
        String StrMontant = jTextField4.getText();
        
        if(Matricule == null || Matricule.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir le matricule");
            return;
        }
        if(Objet == null || Objet.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir l'objet");
            return;
        }
        if(StrMontant ==null || StrMontant.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir un montant valide");
            return;
        }
        if(Mois == null || Mois.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez choisir un mois ");
            return;
        }
        
        float montant = Float.parseFloat(StrMontant);
        if(montant<=0){
            JOptionPane.showMessageDialog(null, "Veuillez remplir un montant valide");
            return;
        }
        
        TraitementCaisse tc = new TraitementCaisse();
        if (tc.verifMoisPaiementEtudiant(Matricule, Mois, Objet)>0) {
            JOptionPane.showMessageDialog(null, "Le paiement pour ce mois et ce type a déjà été effectué.");
            return;
        }
        
        String moisNonPaye = tc.getPremierMoisNonPaye(Matricule, Objet);
if (moisNonPaye != null) {
    String[] listeMois = { "Octobre", "Novembre", "Decembre", "Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet" };
    int indexCourant = java.util.Arrays.asList(listeMois).indexOf(Mois);
    int indexManquant = java.util.Arrays.asList(listeMois).indexOf(moisNonPaye);

    if (indexManquant < indexCourant) {
        JOptionPane.showMessageDialog(null, "Veuillez d'abord payer le mois : " + moisNonPaye);
        return;
    }
}

        
//        if (tc.verifMoisPaiementEtudiant(Matricule, Mois, Objet)==0) {
//            JOptionPane.showMessageDialog(null, "Le paiement du mois precedent n'est pas encore effectué.");
//            return;
//        }
        //String moisPrecedent = tc.getMoisPrecedent(StrMontant);
        //Verification du mois precedent
        
        
        
        if (tc.verifMoisPaiementEtudiant(Matricule, Mois, Objet)>0) {
            JOptionPane.showMessageDialog(null, "Le paiement pour ce mois et ce type a déjà été effectué.");
            return;
        }
        
        boolean resp = tc.ajouterPaiement(Matricule, "",montant,"PAYE", Mois, Objet);

//        boolean success = tp.ajouterPaiement(id, idetudiant, idcaissier, Montant, Date, Statut, Paiement, Mois);
        if (resp) {
            JOptionPane.showMessageDialog(null, "Paiement enregistré avec succès !");
        } else {
            JOptionPane.showMessageDialog(null, "Erreur lors de l'enregistrement du paiement.");
        }


        
        
        
        
                
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
//    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//
//        //Boutton rechercher
//        String matricule =jTextField1.getText();
//        TraitementPaiement tp = new TraitementPaiement();
//        Etudiant etudiant = tp.rechercherEtudiant(matricule);
//        if(etudiant==null){
//            // Creer un message derreur 
//            return;
//        }
//        
//        jTextField2.setText(etudiant.getPrenom());
//        jTextField3.setText(etudiant.getNom());
//        String Filiere =jComboBox1.getSelectedItem().toString();
//        String Niveau =jComboBox2.getSelectedItem().toString();
//    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaisseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaisseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaisseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaisseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaisseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
